services:
  - type: web
    name: aerodyne-compressors
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: ConnectionStrings__ApplicationDbContextConnection
        value: Data Source=aerodyne.db
      - key: SmtpSettings__Server
        value: smtp.gmail.com
      - key: SmtpSettings__Port
        value: "587"
      - key: SmtpSettings__SenderName
        value: AERODYNE EQUIPMENTS
      - key: SmtpSettings__SenderEmail
        sync: false
      - key: SmtpSettings__ReceiverEmail
        sync: false
      - key: SmtpSettings__Password
        sync: false
